networks:
  default: development

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.0

compiler:
  solc:
    version: 0.6.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.2.0"

autofetch_sources: true